### PR TITLE
arm64: Use Mongo4.2, dumb-init and keep image size small

### PR DESCRIPTION
**Pull request by difince**
Fix: https://github.com/edgexfoundry/docker-edgex-mongo/issues/46
And start using dumb-init - addressing issue https://github.com/edgexfoundry/docker-edgex-mongo/issues/37  

@cloudxxx8 Thanks in advance for helping test this issue
Signed-off-by: difince <dianaa@vmware.com>

### CODE REVIEW

**Comment by cloudxxx8** [comment]
I will verify this on my Raspberry Pi next week.  Should it be part of fuji?

**Comment by cloudxxx8** [comment]
Sorry for the delay, and we are working on this next week

**Comment by difince** [comment]
@cloudxxx8 
I already have a Rasperry Pi 3 B+, so I tested this PR by my own and I successful built an image via this command:
`ubuntu:~/docker-edgex-mongo$ docker build -f cmd/Dockerfile.aarch64 -t edgexfoundry/docker-edgex-mongo:dev  .`

I want to emphasize that I was in `docker-edgex-mongo` directory, not in the `cmd`.  
I suggested You have been in the `cmd` directory and this is why you got` COPY failed: stat /var/lib/docker/tmp/docker-builder627301018/go.mod: no such file or directory` exception.
Even more if we just execute 'docker build' it is supposed to execute the default  Dockerfile, not Dockerfile.aarch64

In addition, in the [Make](https://github.com/edgexfoundry/docker-edgex-mongo/blob/526f9252d9bfa24d0049138afd50f986d932d92d/Makefile#L55) file I have rule for building  `edgex-mongo `,  but I am missing a rule for building edgex-mongo for ARM devices, that is why I was using the long command
 `ubuntu:~/docker-edgex-mongo$ docker build -f cmd/Dockerfile.aarch64 -t edgexfoundry/docker-edgex-mongo:dev  .`
I could open an issue for - adding new rule for building ARM images 'edgex-mongo-arm'. So the next time, we could execute directly:
` ~/docker-edgex-mongo$ make edgex-docker-arm `

**Comment by cloudxxx8** [comment]
sounds great.
I just assigned to @jinlinGuan , and she will also verified the built Mongo image by running blackbox test locally

**Comment by cloudxxx8** [comment]
We will verify it works by next week.  Sorry for the delay.

**Comment by difince** [comment]
Thank you @cloudxxx8

**Comment by jinlinGuan** [comment]
LGTM
I've verified with core-data blackbox test, and everything works fine.

**Comment by difince** [comment]
Because mongo has released arm64 images under the same tag cmd/Dockerfile.aarch64 have been removed by PR #76.
#76 (comment)
That is why this issue is not relevant anymore.

**Pull request closed without merging**
